name: Mirror Repository

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MengYYY369/my_verifier.git
          git push --mirror gitlab

      - name: Push to Gitee
        run: |
          git remote add gitee https://${{ secrets.GITEE_TOKEN }}@gitee.com/MengYYY666/My_Verifier.git
          git push --mirror gitee

      - name: Push to GitCode
        run: |
          git remote add gitcode https://${{ secrets.GITCODE_TOKEN }}@gitcode.com/2301_76858796/My_Verifier.git
          git push --mirror gitcode