name: Mirror Repository

permissions:
  contents: read

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get Branch Name
        id: branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
      
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      
          chmod 600 ~/.ssh/id_ed25519
      
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts 2>/dev/null || true

      # GitLab
      - name: Push to GitLab
        continue-on-error: true
        run: |
          git remote remove gitlab || true

          # HTTPS first
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MengYYY369/my_verifier.git

          if ! git push gitlab HEAD:${{ steps.branch.outputs.branch }}; then
            echo "HTTPS failed, fallback to SSH..."

            git remote remove gitlab
            git remote add gitlab git@gitlab.com:MengYYY369/my_verifier.git

            git push gitlab HEAD:${{ steps.branch.outputs.branch }}
          fi

          git push --tags gitlab || true

      # Gitee
      - name: Push to Gitee
        continue-on-error: true
        run: |
          git remote remove gitee || true

          # HTTPS first
          git remote add gitee https://MengYYY666:${{ secrets.GITEE_TOKEN }}@gitee.com/MengYYY666/My_Verifier.git

          if ! git push gitee HEAD:${{ steps.branch.outputs.branch }}; then
            echo "HTTPS failed, fallback to SSH..."

            git remote remove gitee
            git remote add gitee git@gitee.com:MengYYY666/My_Verifier.git

            git push gitee HEAD:${{ steps.branch.outputs.branch }}
          fi

          git push --tags gitee || true

      # GitCode
      - name: Push to GitCode
        continue-on-error: true
        run: |
          git remote remove gitcode || true

          # HTTPS first
          git remote add gitcode https://2301_76858796:${{ secrets.GITCODE_TOKEN }}@gitcode.com/2301_76858796/My_Verifier.git

          if ! git push gitcode HEAD:${{ steps.branch.outputs.branch }}; then
            echo "HTTPS failed, fallback to SSH..."

            git remote remove gitcode
            git remote add gitcode git@gitcode.com:2301_76858796/My_Verifier.git

            git push gitcode HEAD:${{ steps.branch.outputs.branch }}
          fi

          git push --tags gitcode || true
